# Generated by Django 4.2.11 on 2024-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
